var headerConfig = [
    {path:"module/analysis/risk/map.html",title:"风险地图",backUrl:"/module/analysis/index.html",index:2},
    {path:"module/analysis/risk/calendar.html",title:"风险月历",backUrl:"/module/analysis/index.html",index:2},
    {path:"module/analysis/safetyInspection/home.html",title:"安全巡检",backUrl:"/module/analysis/index.html",index:2},
    {path:"module/analysis/safetyInspection/add.html",title:"保存巡检任务安排",backUrl:"/module/analysis/safetyInspection/home.html",index:2},
    {path:"module/emergency/index.html",title:"预案与演练",backUrl:"/module/home/index.html",index:1},
    {path:"module/emergency/aidGroups.html",title:"应急救援组织架构图",backUrl:"/module/emergency/index.html",index:1},
    {path:"module/emergency/emergencyCard.html",title:"岗位安全应急卡",backUrl:"/module/emergency/aidGroups.html",index:1},
    {path:"module/emergency/emergencyPlan/budgetManage.html",title:"应急预案管理",backUrl:"/module/emergency/index.html",index:1},
    {path:"module/emergency/emergencyPlan/save.html",title:"新增应急预案",backUrl:"/module/emergency/emergencyPlan/budgetManage.html",index:1},
    {path:"module/emergency/rehearse/plan.html",title:"应急演练计划",backUrl:"/module/emergency/index.html",index:1},
    {path:"module/emergency/rehearse/createPlan.html",title:"创建应急演练计划",backUrl:"/module/emergency/rehearse/plan.html",index:1},
    {path:"module/emergency/figure/location.html",title:"应急演练线路图",backUrl:"/module/emergency/index.html",index:1},
    {path:"module/emergency/rehearse/start.html",title:"启动演练计划",backUrl:"/module/emergency/rehearse/plan.html",index:1},
    {path:"module/analysis/incident/statistic.html",title:"校内外事件统计",backUrl:"/module/analysis/index.html",index:2},
    {path:"module/analysis/index.html",title:"评估与分析",backUrl:"/module/home/index.html",index:2},
    {path:"module/emergency/rehearse/addPerson.html",title:"应急联系人维护",backUrl:"/module/emergency/rehearse/start.html",index:1},
    {path:"module/analysis/incident/record.html",title:"突发事件记录",backUrl:"/module/analysis/incident/statistic.html",index:2},
    {path:"module/analysis/hiddenTrouble/readilyReported.html",title:"隐患随手曝",backUrl:"/module/analysis/index.html",index:2},
    {path:"module/analysis/hiddenTrouble/add.html",title:"隐患随手曝 上报",backUrl:"/module/analysis/hiddenTrouble/readilyReported.html",index:2},
    {path:"module/analysis/hiddenTrouble/acceptance.html",title:"隐患随手曝 验收",backUrl:"/module/analysis/hiddenTrouble/readilyReported.html",index:2},
    {path:"module/safetyManage/index.html",title:"档案与管理",backUrl:"/module/home/index.html",index:3},
    {path:"module/safetyManage/schoolInfo.html",title:"学校基本信息",backUrl:"/module/safetyManage/index.html",index:3},
    {path:"module/safetyManage/editSchoolInfo.html",title:"编辑学校基本信息",backUrl:"/module/safetyManage/schoolInfo.html",index:3},
    {path:"module/safetyManage/gzSystem.html",title:"安全管理规章制度",backUrl:"/module/safetyManage/index.html",index:3},
    {path:"module/safetyManage/system.html",title:"安全管理责任体系",backUrl:"/module/safetyManage/index.html",index:3},
    {path:"module/safetyManage/specUpload.html",title:"规章制度上传",backUrl:"/module/safetyManage/gzSystem.html",index:3},
    {path:"module/safetyManage/infoCard/cardManage.html",title:"信息卡管理",backUrl:"/module/safetyManage/index.html",index:3},
    {path:"module/safetyManage/infoCard/classList.html",title:"班级管理",backUrl:"/module/safetyManage/infoCard/cardManage.html",index:3},
    {path:"module/safetyManage/infoCard/studentList.html",title:"学生管理",backUrl:"-1",index:3},
    {path:"module/safetyManage/infoCard/studentCard.html",title:"学生卡",backUrl:"/module/safetyManage/infoCard/cardManage.html",index:3},
    {path:"module/safetyManage/addressBook/addressBook.html",title:"通讯录",backUrl:"/module/safetyManage/index.html",index:3},
    {path:"module/safetyManage/addressBook/contactList.html",title:"联系人列表",backUrl:"/module/safetyManage/addressBook/addressBook.html",index:3},
    {path:"module/safetyManage/announcementNotice.html",title:"公告通知",backUrl:"/module/safetyManage/index.html",index:3},
    {path:"module/safetyManage/noticeWaitApprove.html",title:"公告通知-待审核列表",backUrl:"/module/safetyManage/announcementNotice.html",index:3},
    {path:"module/safetyManage/notice.html",title:"发布公告通知",backUrl:"/module/safetyManage/announcementNotice.html",index:3},
    {path:"module/safetyManage/approveNotice.html",title:"公告通知-审核",backUrl:"/module/safetyManage/noticeWaitApprove.html",index:3},
    {path:"module/safetyManage/knowledge/policyHot.html",title:"政策知识",backUrl:"/module/safetyManage/index.html",index:3},
    {path:"module/safetyManage/knowledge/socialHot.html",title:"社会热点",backUrl:"/module/safetyManage/index.html",index:3},
    {path:"module/safetyManage/knowledge/searchKnowledge.html",title:"知识库搜索",backUrl:"/module/safetyManage/index.html",index:3},
    {path:"module/safetyManage/knowledge/socialHotDetail.html",title:"详情",backUrl:"-1",index:3},
    {path:"module/analysis/risk/add.html",title:"维护风险案例",backUrl:"/module/analysis/risk/map.html",index:2},
    {path:"module/analysis/risk/addMonth.html",title:"添加风险月历",backUrl:"/module/analysis/risk/calendar.html",index:2},
    {path:"module/home/detail.html",title:"关爱留守儿童",backUrl:"/module/home/index.html",index:0},
    {path:"module/home/index.html",title:"首页",backUrl:"#",index:0,isHomePage:true},
    {path:"module/analysis/risk/case.html",title:"风险案例及防控",backUrl:"/module/analysis/risk/map.html",index:2},
    {path:"module/analysis/hiddenTrouble/feedback.html",title:"随手曝处理，反馈",backUrl:"/module/analysis/hiddenTrouble/readilyReported.html",index:2},
    {path:"module/analysis/safetyInspection/listTwo.html",title:"安全巡检项",backUrl:"/module/analysis/safetyInspection/home.html",index:2},
    {path:"module/analysis/safetyInspection/listThree.html",title:"安全巡检项",backUrl:"-1",index:2},
    {path:"module/analysis/safetyInspection/list.html",title:"安全巡检历史任务",backUrl:"/module/analysis/safetyInspection/home.html",index:2},
    {path:"module/analysis/safetyInspection/taskPlan.html",title:"巡检任务安排列表",backUrl:"/module/analysis/safetyInspection/home.html",index:2},
    {path:"module/analysis/safetyInspection/submit.html",title:"安全巡检提交",backUrl:"-1",index:2},
    {path:"module/analysis/safetyInspection/assign.html",title:"指派任务",backUrl:"-1",index:2},
    {path:"module/analysis/safetyInspection/change.html",title:"处理任务",backUrl:"-1",index:2},
    {path:"module/safetyManage/infoCard/studentInfo.html",title:"学生基本信息",backUrl:"/module/safetyManage/infoCard/studentList.html",index:3},
    {path:"module/analysis/safetyInspection/check.html",title:"验收任务",backUrl:"-1",index:2},
    {path:"module/safetyManage/addSystem.html",title:"新增岗位责任卡",backUrl:"/module/safetyManage/system.html",index:2},
    {path:"module/emergency/emergencyPlan/process.html",title:"应急演练流程图",backUrl:"/module/emergency/index.html",index:1},
    {path:"module/emergency/emergencyPlan/processAdd.html",title:"添加应急演练流电话号码",backUrl:"/module/emergency/emergencyPlan/process.html",index:1},
]
var headerIcons = {
    "1":"icon-xiazai",
    "2":"icon-fenxiang",
    "3":"icon-xin",
    '4':'icon-add'
}

var COOKIEKEY = {
    "education":"0",//学校
    "school":"1"    //教委
}

var SCHOOLID = "21234";